# Generated by Django 5.2.6 on 2025-09-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dummy",
        ),
    ]
