# Generated by Django 5.2.6 on 2025-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_delete_dummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
